name: dance_studio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.1
  image_picker: ^0.8.7+4
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  image_path: "assets/images/AppIcon2.png"  # Path to your icon image
  android: true
  ios: true
  remove_alpha_ios: true  # Removes alpha channel for iOS icons

flutter:
  uses-material-design: true

  assets:
     - assets/images/google_logo.png
     - assets/images/facebook_logo.png
     - assets/images/apple_logo.png
     - assets/images/bannerimage.png
     - assets/images/course1.png
     - assets/images/course2.png
     - assets/images/course3.png
     - assets/images/event1.png
     - assets/images/event2.png
     - assets/images/event3.png
     - assets/images/brandlogo.png
     - assets/images/BCempty_state.png
     - assets/images/rishika_greencircle.png
     - assets/images/winter_greencircle.png
     - assets/images/tommy_greencircle.png
     - assets/images/kurt_redcircle.png
     - assets/images/apple_pay.png
     - assets/images/credit_card.png
     - assets/images/afterpay.png
     - assets/images/credit_balance.png
     - assets/images/Cempty_state.png
     - assets/images/splashlogo.png
     - assets/images/BlueLogo.png
     - assets/images/RedLogo.png
     - assets/images/Avatar.png
     - assets/images/dance-3.png
     - assets/images/AppIcon.png
     - assets/images/AppIcon2.png
     - assets/images/settings.png
     - assets/images/history.png
     - assets/images/payment.png
     - assets/images/about.png
     - assets/images/privacy.png
     - assets/images/help.png
     - assets/images/logout.png
     - assets/images/membership.png
     - assets/images/chantelle.png
     - assets/images/ivy.png
     - assets/images/janey.png
     - assets/images/jeff.png
     - assets/images/kurt.png
     - assets/images/oliver.png
     - assets/images/rishika.png
     - assets/images/taymane.png
     - assets/images/tommy.png
     - assets/images/tracey.png
     - assets/images/winter.png
     - assets/images/kidsdc1.png
     - assets/images/kidsdc2.png
     - assets/images/beginnercourse.png
     - assets/images/intcourse.png
     - assets/images/kidscourse.png
     - assets/images/popupcourse.png
     - assets/images/smallstudio.png
     - assets/images/bigstudio.png
